import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  container: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '0 20px',
  },
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    background: 'rgba(17, 17, 17, 0.95)',
    backdropFilter: 'blur(10px)',
    borderBottom: '1px solid #333',
    padding: '15px 0',
  },
  noLocation: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
    background: 'radial-gradient(circle at 70% 50%, rgba(247, 147, 30, 0.1) 0%, transparent 60%)',
    color: '#111',
  },
  noLocationContent: {
    maxWidth: 520,
    width: '100%',
    textAlign: 'center',
    padding: '32px',
    borderRadius: '18px',
    boxShadow: '0 20px 60px rgba(255, 255, 255, 0.12)',
    border: '1px solid rgba(15, 23, 42, 0.08)',
  },
  nav: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logo: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '2rem',
    letterSpacing: '2px',
  },
  logoOrange: {
    color: 'var(--orange)',
  },
  logoText: {
    color: 'var(--white)',
  },
  navLinks: {
    display: 'flex',
    gap: 30,
    alignItems: 'center',
    alignContent: 'center',
    margin: 'auto',
  },
  navLink: {
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 500,
    fontSize: '0.9rem',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    color: 'var(--white)',
    transition: 'var(--transition)',
    position: 'relative',
  },
  hero: {
    position: 'relative',
    minHeight: '90vh',
    display: 'flex',
    alignItems: 'center',
    background: 'linear-gradient(135deg, #111111 0%, #1a1a1a 100%)',
    overflow: 'hidden',
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: 'radial-gradient(circle at 70% 50%, rgba(247, 147, 30, 0.1) 0%, transparent 60%)',
    pointerEvents: 'none',
  },
  heroContent: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 60,
    alignItems: 'center',
    position: 'relative',
    zIndex: 2,
    padding: '80px 20px',
  },
  heroText: {
    display: 'flex',
    flexDirection: 'column',
  },
  heroTextH2: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '2rem',
    color: 'var(--orange)',
    marginBottom: 10,
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  heroTextH1: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '5rem',
    lineHeight: 1,
    marginBottom: 20,
    background: 'linear-gradient(to right, #ffffff, #FFC04D)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  heroTextP: {
    fontSize: '1.1rem',
    color: '#ccc',
    marginBottom: 30,
    maxWidth: 400,
    lineHeight: 1.6,
  },
  heroImage: {
    display: 'flex',
    justifyContent: 'center',
  },
  heroImageImg: {
    borderRadius: 20,
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.5)',
    transform: 'rotate(3deg)',
    transition: 'var(--transition)',
    width: '100%',
  },
  features: {
    background: 'var(--dark-grey)',
    padding: '60px 0',
    borderTop: '1px solid #333',
    borderBottom: '1px solid #333',
  },
  featuresContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 30,
  },
  feature: {
    textAlign: 'center',
    padding: 20,
    fontSize: '2.5rem',
  },
  featureH3: {
    marginTop: 15,
    fontSize: '1.2rem',
    color: 'var(--white)',
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  sectionH2: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '3rem',
    textAlign: 'center',
    marginBottom: 40,
    color: 'var(--white)',
    position: 'relative',
    display: 'inline-block',
    width: '100%',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  featured: {
    padding: '80px 0',
  },
  menu: {
    padding: '80px 0',
  },
  featuredGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: 30,
  },
  productGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: 30,
  },
  categoryButtons: {
    display: 'flex',
    justifyContent: 'center',
    gap: 15,
    marginBottom: 40,
    flexWrap: 'wrap',
  },
  categoryButton: {
    background: 'var(--dark-grey)',
    border: '1px solid #444',
    color: 'var(--white)',
    padding: '10px 25px',
    borderRadius: 50,
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'var(--transition)',
    textTransform: 'uppercase',
    fontSize: '0.85rem',
  },
  categoryButtonActive: {
    background: 'var(--orange)',
    borderColor: 'var(--orange)',
    color: 'var(--black)',
  },
  about: {
    padding: '80px 0',
    background: 'var(--dark-grey)',
  },
  aboutGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 60,
    alignItems: 'center',
  },
  aboutText: {
    display: 'flex',
    flexDirection: 'column',
  },
  aboutH2: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '3rem',
    textAlign: 'left',
    marginBottom: 20,
    color: 'var(--white)',
    position: 'relative',
    display: 'inline-block',
    width: '100%',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  aboutP: {
    color: '#ccc',
    fontSize: '1.1rem',
    lineHeight: 1.8,
  },
  aboutImage: {
    display: 'flex',
    justifyContent: 'center',
  },
  aboutImg: {
    borderRadius: 16,
    boxShadow: '0 10px 40px rgba(0, 0, 0, 0.4)',
    width: '100%',
  },
  footerSection: {
    background: '#0a0a0a',
    padding: '50px 0 30px',
    borderTop: '1px solid #333',
  },
  footer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 30,
    textAlign: 'center',
  },
  footerCol: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  footerH3: {
    color: 'var(--orange)',
    fontSize: '1.3rem',
    marginBottom: 10,
    fontFamily: "'Bebas Neue', sans-serif",
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  footerP: {
    color: '#888',
    fontSize: '0.95rem',
    lineHeight: 1.6,
  },
  modalBody: {
    flexGrow: 1,
    overflowY: 'auto',
    padding: '20px 25px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  modalFooter: {
    padding: '25px',
    borderTop: '1px solid #333',
    flexShrink: 0,
  },
  cartEmpty: {
    textAlign: 'center',
    padding: '40px 20px',
    color: '#666',
  },
  cartEmptyEmoji: {
    fontSize: '3rem',
    marginBottom: '10px',
  },
  cartItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '15px',
    background: 'var(--dark-grey)',
    borderRadius: '10px',
    border: '1px solid #333',
  },
  cartItemInfo: {
    display: 'flex',
    flexDirection: 'column',
  },
  cartItemName: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '1rem',
    marginBottom: '5px',
  },
  cartItemPrice: {
    color: 'var(--orange)',
    fontWeight: 600,
    margin: 0,
  },
  cartItemActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  cartActionBtn: {
    background: '#333',
    border: 'none',
    color: 'var(--white)',
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    cursor: 'pointer',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeBtn: {
    background: 'transparent',
    border: '1px solid #572a2a',
    color: '#ff8a8a',
    width: 'auto',
    padding: '4px 10px',
    borderRadius: '20px',
    fontSize: '0.75rem',
    cursor: 'pointer',
  },
  editBtn: {
    background: 'transparent',
    border: '1px solid #2a572a',
    color: '#8aff8a',
    width: 'auto',
    padding: '4px 10px',
    borderRadius: '20px',
    fontSize: '0.75rem',
    cursor: 'pointer',
  },
  cartTotalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '8px',
    color: '#aaa',
    fontSize: '0.9rem',
  },
  locationText: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: '0.8rem',
    color: 'var(--orange)',
    marginTop: -10,
  },
  cartTotalFinal: {
    display: 'flex',
    justifyContent: 'space-between',
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '1.3rem',
    color: 'var(--white)',
    marginBottom: '20px',
  },
  cartTotalValue: {
    color: 'var(--orange)',
  },
  cartActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  successScreen: {
    textAlign: 'center',
    padding: '40px 20px',
  },
  successIcon: {
    fontSize: '4rem',
    color: '#4caf50',
    marginBottom: '10px',
  },
  orderNumber: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '2rem',
    color: 'var(--white)',
    margin: '20px 0',
  },
  editButton: {
    background: 'transparent',
    border: '1px solid rgba(247,147,30,0.4)',
    borderRadius: 6,
    color: '#F7931E',
    fontSize: '0.72rem',
    padding: '3px 9px',
    cursor: 'pointer',
    fontFamily: 'Poppins, sans-serif',
    letterSpacing: '0.03em',
    flexShrink: 0,
    transition: 'all 0.15s',
  }
}